# Generated by Django 4.2.4 on 2023-10-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_allowedfield_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedfield',
            name='name',
            field=models.SlugField(),
        ),
    ]
