# Generated by Django 4.2.4 on 2023-10-26 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_filter_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='segment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='contacts.segment'),
        ),
    ]
