# Generated by Django 4.2.4 on 2023-10-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_group_segment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='name',
        ),
        migrations.AddField(
            model_name='filter',
            name='comparator',
            field=models.CharField(choices=[('eq', 'equals'), ('neq', 'not equals')], default='eq', max_length=20),
        ),
    ]
