# Generated by Django 4.2.4 on 2023-11-19 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_remove_filter_name_filter_comparator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='filters',
        ),
        migrations.AddField(
            model_name='contact',
            name='is_unsubscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='unsubscribed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='segment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='contacts.segment'),
        ),
    ]
