# Generated by Django 4.2.4 on 2024-01-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_create_cusom_user_perms"),
        ("contacts", "0011_alter_contact_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("email", "belongs_to")},
        ),
    ]
