# Generated by Django 4.2.4 on 2024-05-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_create_cusom_user_perms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="address",
        ),
        migrations.RemoveField(
            model_name="company",
            name="city",
        ),
        migrations.RemoveField(
            model_name="company",
            name="country",
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
