# Generated by Django 4.2.4 on 2023-12-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportlog",
            name="total_columns",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exportlog",
            name="total_rows",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exportlog",
            name="type",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
