from django.db import models


class CrawlStatus(models.TextChoices):
    """List of all possible crawl status."""
    PENDING = "PENDING", "The crawl is pending."
    RUNNING = "RUNNING", "The crawl is running."
    SUCCESS = "SUCCESS", "The crawl has been successfully done."
    FAILED = "FAILED", "The crawl failed."


class AuditChoices(models.TextChoices):
    """
    List of all available audits ran daily on all pages of a website.

    Each value is a tuple meaning :
        1. The name of the audit.
        2. The category of the audit.
        3. The weight of the audit in the category score.
        4. The weight of the audit in the overall score.
        5. The path to get the value from the Google Page Speed Insights audit (in json).
        6. A description of the audit.
    """
    CRAWL_DEPTH = ("CRAWL_DEPTH", "seo", 0, 1, None, "The current crawl depth of the page.", "CRAWL_DEPTH")
    HAS_URL_ISSUES = ("HAS_URL_ISSUES",  "seo", 0, 1, None, "The crawled page has URL issues: non ascii char, params, space.", "HAS_URL_ISSUES")
    HAS_ONLY_ONE_H1 = ("HAS_ONLY_ONE_H1", "seo", 0, 1, None, "The crawled page has only one H1 tag.", "HAS_ONLY_ONE_H1")

    # Google Page Speed insights Performance metrics/audits
    PSI_PERFORMANCE_SCORE = ("PSI_PERFORMANCE_SCORE",  "perf", 0, 1, "categories.performance.score", "The Google Page Speed Insights performance score.", "PERFORMANCE_SCORE")
    PSI_FIRST_CONTENTFUL_PAINT = ("PSI_FIRST-CONTENTFUL-PAINT", "perf", 10, 1, "audits.first-contentful-paint.score", "First Contentful Paint marks the time at which the first text or image is painted. [Learn more about the First Contentful Paint metric](https://developer.chrome.com/docs/lighthouse/performance/first-contentful-paint/).", "FIRST_CONTENTFUL_PAINT")
    PSI_LARGEST_CONTENTFUL_PAINT = ("PSI_LARGEST-CONTENTFUL-PAINT", "perf", 25, 1, "audits.largest-contentful-paint.score", "Largest Contentful Paint marks the time at which the largest text or image is painted. [Learn more about the Largest Contentful Paint metric](https://developer.chrome.com/docs/lighthouse/performance/lighthouse-largest-contentful-paint/)", "LARGEST_CONTENTFUL_PAINT")
    PSI_TOTAL_BLOCKING_TIME = ("PSI_TOTAL-BLOCKING-TIME", "perf", 30, 1, "audits.total-blocking-time.score", "Sum of all time periods between FCP and Time to Interactive, when task length exceeded 50ms, expressed in milliseconds. [Learn more about the Total Blocking Time metric](https://developer.chrome.com/docs/lighthouse/performance/lighthouse-total-blocking-time/).", "TOTAL_BLOCKING_TIME")
    PSI_CUMULATIVE_LAYOUT_SHIFT = ("PSI_CUMULATIVE-LAYOUT-SHIFT", "perf", 25, 1, "audits.cumulative-layout-shift.score", "Cumulative Layout Shift measures the movement of visible elements within the viewport. [Learn more about the Cumulative Layout Shift metric](https://web.dev/articles/cls).", "CUMULATIVE_LAYOUT_SHIFT")
    PSI_SPEED_INDEX = ("PSI_SPEED-INDEX", "perf", 10, 1, "audits.speed-index.score", "Speed Index shows how quickly the contents of a page are visibly populated. [Learn more about the Speed Index metric](https://developer.chrome.com/docs/lighthouse/performance/speed-index/).", "SPEED_INDEX")
    PSI_INTERACTIVE = ("PSI_INTERACTIVE", "perf", 0, 1, "audits.interactive.score", "Time to Interactive is the amount of time it takes for the page to become fully interactive. [Learn more about the Time to Interactive metric](https://developer.chrome.com/docs/lighthouse/performance/interactive/).", "INTERACTIVE")
    PSI_MAX_POTENTIAL_FID = ("PSI_MAX-POTENTIAL-FID", "perf", 0, 1, "audits.max-potential-fid.score", "The maximum potential First Input Delay that your users could experience is the duration of the longest task. [Learn more about the Maximum Potential First Input Delay metric](https://developer.chrome.com/docs/lighthouse/performance/lighthouse-max-potential-fid/).", "MAX_POTENTIAL_FID")
    PSI_FIRST_MEANINGFUL_PAINT = ("PSI_FIRST-MEANINGFUL-PAINT", "perf", 0, 1, "audits.first-meaningful-paint.score", "First Meaningful Paint measures when the primary content of a page is visible. [Learn more about the First Meaningful Paint metric](https://developer.chrome.com/docs/lighthouse/performance/first-meaningful-paint/).", "FIRST_MEANINGFUL_PAINT")
    PSI_RENDER_BLOCKING_RESOURCES = ("PSI_RENDER-BLOCKING-RESOURCES", "perf", 0, 1, "audits.render-blocking-resources.score", "Resources are blocking the first paint of your page. Consider delivering critical JS/CSS inline and deferring all non-critical JS/styles. [Learn how to eliminate render-blocking resources](https://developer.chrome.com/docs/lighthouse/performance/render-blocking-resources/).", "RENDER_BLOCKING_RESOURCES")
    PSI_USES_RESPONSIVE_IMAGES = ("PSI_USES-RESPONSIVE-IMAGES", "perf", 0, 1, "audits.uses-responsive-images.score", "Serve images that are appropriately-sized to save cellular data and improve load time. [Learn how to size images](https://developer.chrome.com/docs/lighthouse/performance/uses-responsive-images/).", "USES_RESPONSIVE_IMAGES")
    PSI_OFFSCREEN_IMAGES = ("PSI_OFFSCREEN-IMAGES", "perf", 0, 1, "audits.offscreen-images.score", "Consider lazy-loading offscreen and hidden images after all critical resources have finished loading to lower time to interactive. [Learn how to defer offscreen images](https://developer.chrome.com/docs/lighthouse/performance/offscreen-images/).", "OFFSCREEN_IMAGES")
    PSI_UNMINIFIED_CSS = ("PSI_UNMINIFIED-CSS", "perf", 0, 1, "audits.unminified-css.score", "Minifying CSS files can reduce network payload sizes. [Learn how to minify CSS](https://developer.chrome.com/docs/lighthouse/performance/unminified-css/).", "UNMINIFIED_CSS")
    PSI_UNMINIFIED_JAVASCRIPT = ("PSI_UNMINIFIED-JAVASCRIPT", "perf", 0, 1, "audits.unminified-javascript.score", "Minifying JavaScript files can reduce payload sizes and script parse time. [Learn how to minify JavaScript](https://developer.chrome.com/docs/lighthouse/performance/unminified-javascript/).", "UNMINIFIED_JAVASCRIPT")
    PSI_UNUSED_CSS_RULES = ("PSI_UNUSED-CSS-RULES", "perf", 0, 1, "audits.unused-css-rules.score", "Reduce unused rules from stylesheets and defer CSS not used for above-the-fold content to decrease bytes consumed by network activity. [Learn how to reduce unused CSS](https://developer.chrome.com/docs/lighthouse/performance/unused-css-rules/).", "UNUSED_CSS_RULES")
    PSI_UNUSED_JAVASCRIPT = ("PSI_UNUSED-JAVASCRIPT", "perf", 0, 1, "audits.unused-javascript.score", "Reduce unused JavaScript and defer loading scripts until they are required to decrease bytes consumed by network activity. [Learn how to reduce unused JavaScript](https://developer.chrome.com/docs/lighthouse/performance/unused-javascript/).", "UNUSED_JAVASCRIPT")
    PSI_USES_OPTIMIZED_IMAGES = ("PSI_USES-OPTIMIZED-IMAGES", "perf", 0, 1, "audits.uses-optimized-images.score", "Optimized images load faster and consume less cellular data. [Learn how to efficiently encode images](https://developer.chrome.com/docs/lighthouse/performance/uses-optimized-images/).", "USES_OPTIMIZED_IMAGES")
    PSI_MODERN_IMAGE_FORMATS = ("PSI_MODERN-IMAGE-FORMATS", "perf", 0, 1, "audits.modern-image-formats.score", "Image formats like WebP and AVIF often provide better compression than PNG or JPEG, which means faster downloads and less data consumption. [Learn more about modern image formats](https://developer.chrome.com/docs/lighthouse/performance/uses-webp-images/).", "MODERN_IMAGE_FORMATS")
    PSI_USES_TEXT_COMPRESSION = ("PSI_USES-TEXT-COMPRESSION", "perf", 0, 1, "audits.uses-text-compression.score", "Text-based resources should be served with compression (gzip, deflate or brotli) to minimize total network bytes. [Learn more about text compression](https://developer.chrome.com/docs/lighthouse/performance/uses-text-compression/).", "USES_TEXT_COMPRESSION")
    PSI_USES_REL_PRECONNECT = ("PSI_USES-REL-PRECONNECT", "perf", 0, 1, "audits.uses-rel-preconnect.score", "Consider adding `preconnect` or `dns-prefetch` resource hints to establish early connections to important third-party origins. [Learn how to preconnect to required origins](https://developer.chrome.com/docs/lighthouse/performance/uses-rel-preconnect/).", "USES_REL_PRECONNECT")
    PSI_SERVER_RESPONSE_TIME = ("PSI_SERVER-RESPONSE-TIME", "perf", 0, 1, "audits.server-response-time.score", "Keep the server response time for the main document short because all other requests depend on it. [Learn more about the Time to First Byte metric](https://developer.chrome.com/docs/lighthouse/performance/time-to-first-byte/).", "SERVER_RESPONSE_TIME")
    PSI_REDIRECTS = ("PSI_REDIRECTS", "perf", 0, 1, "audits.redirects.score", "Redirects introduce additional delays before the page can be loaded. [Learn how to avoid page redirects](https://developer.chrome.com/docs/lighthouse/performance/redirects/).", "REDIRECTS")
    PSI_USES_HTTP2 = ("PSI_USES-HTTP2", "perf", 0, 1, "audits.uses-http2.score", "HTTP/2 offers many benefits over HTTP/1.1, including binary headers and multiplexing. [Learn more about HTTP/2](https://developer.chrome.com/docs/lighthouse/best-practices/uses-http2/).", "USES_HTTP2")
    PSI_EFFICIENT_ANIMATED_CONTENT = ("PSI_EFFICIENT-ANIMATED-CONTENT", "perf", 0, 1, "audits.efficient-animated-content.score", "Large GIFs are inefficient for delivering animated content. Consider using MPEG4/WebM videos for animations and PNG/WebP for static images instead of GIF to save network bytes. [Learn more about efficient video formats](https://developer.chrome.com/docs/lighthouse/performance/efficient-animated-content/)", "EFFICIENT_ANIMATED_CONTENT")
    PSI_DUPLICATED_JAVASCRIPT = ("PSI_DUPLICATED-JAVASCRIPT", "perf", 0, 1, "audits.duplicated-javascript.score", "Remove large, duplicate JavaScript modules from bundles to reduce unnecessary bytes consumed by network activity. ", "DUPLICATED_JAVASCRIPT")
    PSI_LEGACY_JAVASCRIPT = ("PSI_LEGACY-JAVASCRIPT", "perf", 0, 1, "audits.legacy-javascript.score", "Polyfills and transforms enable legacy browsers to use new JavaScript features. However, many aren't necessary for modern browsers. For your bundled JavaScript, adopt a modern script deployment strategy using module/nomodule feature detection to reduce the amount of code shipped to modern browsers, while retaining support for legacy browsers. [Learn how to use modern JavaScript](https://web.dev/articles/publish-modern-javascript)", "LEGACY_JAVASCRIPT")
    PSI_PRIORITIZE_LCP_IMAGE = ("PSI_PRIORITIZE-LCP-IMAGE", "perf", 0, 1, "audits.prioritize-lcp-image.score", "If the LCP element is dynamically added to the page, you should preload the image in order to improve LCP. [Learn more about preloading LCP elements](https://web.dev/articles/optimize-lcp#optimize_when_the_resource_is_discovered).", "PRIORITIZE_LCP_IMAGE")
    PSI_TOTAL_BYTE_WEIGHT = ("PSI_TOTAL-BYTE-WEIGHT", "perf", 0, 1, "audits.total-byte-weight.score", "Large network payloads cost users real money and are highly correlated with long load times. [Learn how to reduce payload sizes](https://developer.chrome.com/docs/lighthouse/performance/total-byte-weight/).", "TOTAL_BYTE_WEIGHT")
    PSI_USES_LONG_CACHE_TTL = ("PSI_USES-LONG-CACHE-TTL", "perf", 0, 1, "audits.uses-long-cache-ttl.score", "A long cache lifetime can speed up repeat visits to your page. [Learn more about efficient cache policies](https://developer.chrome.com/docs/lighthouse/performance/uses-long-cache-ttl/).", "USES_LONG_CACHE_TTL")
    PSI_DOM_SIZE = ("PSI_DOM-SIZE", "perf", 0, 1, "audits.dom-size.score", "A large DOM will increase memory usage, cause longer [style calculations](https://developers.google.com/web/fundamentals/performance/rendering/reduce-the-scope-and-complexity-of-style-calculations), and produce costly [layout reflows](https://developers.google.com/speed/articles/reflow). [Learn how to avoid an excessive DOM size](https://developer.chrome.com/docs/lighthouse/performance/dom-size/).", "DOM_SIZE")
    PSI_CRITICAL_REQUEST_CHAINS = ("PSI_CRITICAL-REQUEST-CHAINS", "perf", 0, 1, "audits.critical-request-chains.score", "The Critical Request Chains below show you what resources are loaded with a high priority. Consider reducing the length of chains, reducing the download size of resources, or deferring the download of unnecessary resources to improve page load. [Learn how to avoid chaining critical requests](https://developer.chrome.com/docs/lighthouse/performance/critical-request-chains/).", "CRITICAL_REQUEST_CHAINS")
    PSI_USER_TIMINGS = ("PSI_USER-TIMINGS", "perf", 0, 1, "audits.user-timings.score", "Consider instrumenting your app with the User Timing API to measure your app's real-world performance during key user experiences. [Learn more about User Timing marks](https://developer.chrome.com/docs/lighthouse/performance/user-timings/).", "USER_TIMINGS")
    PSI_BOOTUP_TIME = ("PSI_BOOTUP-TIME", "perf", 0, 1, "audits.bootup-time.score", "Consider reducing the time spent parsing, compiling, and executing JS. You may find delivering smaller JS payloads helps with this. [Learn how to reduce Javascript execution time](https://developer.chrome.com/docs/lighthouse/performance/bootup-time/).", "BOOTUP_TIME")
    PSI_MAINTHREAD_WORK_BREAKDOWN = ("PSI_MAINTHREAD-WORK-BREAKDOWN", "perf", 0, 1, "audits.mainthread-work-breakdown.score", "Consider reducing the time spent parsing, compiling and executing JS. You may find delivering smaller JS payloads helps with this. [Learn how to minimize main-thread work](https://developer.chrome.com/docs/lighthouse/performance/mainthread-work-breakdown/)", "MAINTHREAD_WORK_BREAKDOWN")
    PSI_FONT_DISPLAY = ("PSI_FONT-DISPLAY", "perf", 0, 1, "audits.font-display.score", "Leverage the `font-display` CSS feature to ensure text is user-visible while webfonts are loading. [Learn more about `font-display`](https://developer.chrome.com/docs/lighthouse/performance/font-display/).", "FONT_DISPLAY")
    PSI_THIRD_PARTY_SUMMARY = ("PSI_THIRD-PARTY-SUMMARY", "perf", 0, 1, "audits.third-party-summary.score", "Third-party code can significantly impact load performance. Limit the number of redundant third-party providers and try to load third-party code after your page has primarily finished loading. [Learn how to minimize third-party impact](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/).", "THIRD_PARTY_SUMMARY")
    PSI_THIRD_PARTY_FACADES = ("PSI_THIRD-PARTY-FACADES", "perf", 0, 1, "audits.third-party-facades.score", "Some third-party embeds can be lazy loaded. Consider replacing them with a facade until they are required. [Learn how to defer third-parties with a facade](https://developer.chrome.com/docs/lighthouse/performance/third-party-facades/).", "THIRD_PARTY_FACADES")
    PSI_LARGEST_CONTENTFUL_PAINT_ELEMENT = ("PSI_LARGEST-CONTENTFUL-PAINT-ELEMENT", "perf", 0, 1, "audits.largest-contentful-paint-element.score", "This is the largest contentful element painted within the viewport. [Learn more about the Largest Contentful Paint element](https://developer.chrome.com/docs/lighthouse/performance/lighthouse-largest-contentful-paint/)", "LARGEST_CONTENTFUL_PAINT_ELEMENT")
    PSI_LCP_LAZY_LOADED = ("PSI_LCP-LAZY-LOADED", "perf", 0, 1, "audits.lcp-lazy-loaded.score", "Above-the-fold images that are lazily loaded render later in the page lifecycle, which can delay the largest contentful paint. [Learn more about optimal lazy loading](https://web.dev/articles/lcp-lazy-loading).", "LCP_LAZY_LOADED")
    PSI_LAYOUT_SHIFTS = ("PSI_LAYOUT-SHIFTS", "perf", 0, 1, "audits.layout-shifts.score", "These are the largest layout shifts observed on the page. Each table item represents a single layout shift, and shows the element that shifted the most. Below each item are possible root causes that led to the layout shift. Some of these layout shifts may not be included in the CLS metric value due to [windowing](https://web.dev/articles/cls#what_is_cls). [Learn how to improve CLS](https://web.dev/articles/optimize-cls)", "LAYOUT_SHIFTS")
    PSI_USES_PASSIVE_EVENT_LISTENERS = ("PSI_USES-PASSIVE-EVENT-LISTENERS", "perf", 0, 1, "audits.uses-passive-event-listeners.score", "Consider marking your touch and wheel event listeners as `passive` to improve your page's scroll performance. [Learn more about adopting passive event listeners](https://developer.chrome.com/docs/lighthouse/best-practices/uses-passive-event-listeners/).", "USES_PASSIVE_EVENT_LISTENERS")
    PSI_NO_DOCUMENT_WRITE = ("PSI_NO-DOCUMENT-WRITE", "perf", 0, 1, "audits.no-document-write.score", "For users on slow connections, external scripts dynamically injected via `document.write()` can delay page load by tens of seconds. [Learn how to avoid document.write()](https://developer.chrome.com/docs/lighthouse/best-practices/no-document-write/).", "NO_DOCUMENT_WRITE")
    PSI_LONG_TASKS = ("PSI_LONG-TASKS", "perf", 0, 1, "audits.long-tasks.score", "Lists the longest tasks on the main thread, useful for identifying worst contributors to input delay. [Learn how to avoid long main-thread tasks](https://web.dev/articles/long-tasks-devtools)", "LONG_TASKS")
    PSI_NON_COMPOSITED_ANIMATIONS = ("PSI_NON-COMPOSITED-ANIMATIONS", "perf", 0, 1, "audits.non-composited-animations.score", "Animations which are not composited can be janky and increase CLS. [Learn how to avoid non-composited animations](https://developer.chrome.com/docs/lighthouse/performance/non-composited-animations/)", "NON_COMPOSITED_ANIMATIONS")
    PSI_UNSIZED_IMAGES = ("PSI_UNSIZED-IMAGES", "perf", 0, 1, "audits.unsized-images.score", "Set an explicit width and height on image elements to reduce layout shifts and improve CLS. [Learn how to set image dimensions](https://web.dev/articles/optimize-cls#images_without_dimensions)", "UNSIZED_IMAGES")
    PSI_BF_CACHE = ("PSI_BF-CACHE", "perf", 0, 1, "audits.bf-cache.score", "Many navigations are performed by going back to a previous page, or forwards again. The back/forward cache (bfcache) can speed up these return navigations. [Learn more about the bfcache](https://developer.chrome.com/docs/lighthouse/performance/bf-cache/)", "BF_CACHE")
    PSI_NETWORK_REQUESTS = ("PSI_NETWORK-REQUESTS", "perf", 0, 1, "audits.network-requests.score", "Lists the network requests that were made during page load.", "NETWORK_REQUESTS")
    PSI_NETWORK_RTT = ("PSI_NETWORK-RTT", "perf", 0, 1, "audits.network-rtt.score", "Network round trip times (RTT) have a large impact on performance. If the RTT to an origin is high, it's an indication that servers closer to the user could improve performance. [Learn more about the Round Trip Time](https://hpbn.co/primer-on-latency-and-bandwidth/).", "NETWORK_RTT")
    PSI_NETWORK_SERVER_LATENCY = ("PSI_NETWORK-SERVER-LATENCY", "perf", 0, 1, "audits.network-server-latency.score", "Server latencies can impact web performance. If the server latency of an origin is high, it's an indication the server is overloaded or has poor backend performance. [Learn more about server response time](https://hpbn.co/primer-on-web-performance/#analyzing-the-resource-waterfall).", "NETWORK_SERVER_LATENCY")
    PSI_MAIN_THREAD_TASKS = ("PSI_MAIN-THREAD-TASKS", "perf", 0, 1, "audits.main-thread-tasks.score", "Lists the toplevel main thread tasks that executed during page load.", "MAIN_THREAD_TASKS")
    PSI_RESOURCE_SUMMARY = ("PSI_RESOURCE-SUMMARY", "perf", 0, 1, "audits.resource-summary.score", "Aggregates all network requests and groups them by type", "RESOURCE_SUMMARY")
    # Google Page Speed insights Accessibility metrics/audits
    PSI_ACCESSIBILITY_SCORE = ("PSI_ACCESSIBILITY_SCORE", "a11y", 0, 1, "categories.accessibility.score", "The Google Page Speed Insights accessibility score.", "ACCESSIBILITY_SCORE")
    PSI_ACCESSKEYS = ("PSI_ACCESSKEYS", "a11y", 0, 1, "audits.accesskeys.score", "Access keys let users quickly focus a part of the page. For proper navigation, each access key must be unique. [Learn more about access keys](https://dequeuniversity.com/rules/axe/4.9/accesskeys).", "ACCESSKEYS")
    PSI_ARIA_ALLOWED_ATTR = ("PSI_ARIA-ALLOWED-ATTR", "a11y", 10, 1, "audits.aria-allowed-attr.score", "Each ARIA `role` supports a specific subset of `aria-*` attributes. Mismatching these invalidates the `aria-*` attributes. [Learn how to match ARIA attributes to their roles](https://dequeuniversity.com/rules/axe/4.9/aria-allowed-attr).", "ARIA_ALLOWED_ATTR")
    PSI_ARIA_ALLOWED_ROLE = ("PSI_ARIA-ALLOWED-ROLE", "a11y", 1, 1, "audits.aria-allowed-role.score", "ARIA `role`s enable assistive technologies to know the role of each element on the web page. If the `role` values are misspelled, not existing ARIA `role` values, or abstract roles, then the purpose of the element will not be communicated to users of assistive technologies. [Learn more about ARIA roles](https://dequeuniversity.com/rules/axe/4.9/aria-allowed-role).", "ARIA_ALLOWED_ROLE")
    PSI_ARIA_COMMAND_NAME = ("PSI_ARIA-COMMAND-NAME", "a11y", 0, 1, "audits.aria-command-name.score", "When an element doesn't have an accessible name, screen readers announce it with a generic name, making it unusable for users who rely on screen readers. [Learn how to make command elements more accessible](https://dequeuniversity.com/rules/axe/4.9/aria-command-name).", "ARIA_COMMAND_NAME")
    PSI_ARIA_CONDITIONAL_ATTR = ("PSI_ARIA-CONDITIONAL-ATTR", "a11y", 7, 1, "audits.aria-conditional-attr.score", "Some ARIA attributes are only allowed on an element under certain conditions. [Learn more about conditional ARIA attributes](https://dequeuniversity.com/rules/axe/4.9/aria-conditional-attr).", "ARIA_CONDITIONAL_ATTR")
    PSI_ARIA_DEPRECATED_ROLE = ("PSI_ARIA-DEPRECATED-ROLE", "a11y", 1, 1, "audits.aria-deprecated-role.score", "Deprecated ARIA roles may not be processed correctly by assistive technology. [Learn more about deprecated ARIA roles](https://dequeuniversity.com/rules/axe/4.9/aria-deprecated-role).", "ARIA_DEPRECATED_ROLE")
    PSI_ARIA_DIALOG_NAME = ("PSI_ARIA-DIALOG-NAME", "a11y", 0, 1, "audits.aria-dialog-name.score", "ARIA dialog elements without accessible names may prevent screen readers users from discerning the purpose of these elements. [Learn how to make ARIA dialog elements more accessible](https://dequeuniversity.com/rules/axe/4.9/aria-dialog-name).", "ARIA_DIALOG_NAME")
    PSI_ARIA_HIDDEN_BODY = ("PSI_ARIA-HIDDEN-BODY", "a11y", 10, 1, "audits.aria-hidden-body.score", "Assistive technologies, like screen readers, work inconsistently when `aria-hidden='true'` is set on the document `<body>`. [Learn how `aria-hidden` affects the document body](https://dequeuniversity.com/rules/axe/4.9/aria-hidden-body).", "ARIA_HIDDEN_BODY")
    PSI_ARIA_HIDDEN_FOCUS = ("PSI_ARIA-HIDDEN-FOCUS", "a11y", 7, 1, "audits.aria-hidden-focus.score", "Focusable descendents within an `[aria-hidden='true']` element prevent those interactive elements from being available to users of assistive technologies like screen readers. [Learn how `aria-hidden` affects focusable elements](https://dequeuniversity.com/rules/axe/4.9/aria-hidden-focus).", "ARIA_HIDDEN_FOCUS")
    PSI_ARIA_INPUT_FIELD_NAME = ("PSI_ARIA-INPUT-FIELD-NAME", "a11y", 0, 1, "audits.aria-input-field-name.score", "When an input field doesn't have an accessible name, screen readers announce it with a generic name, making it unusable for users who rely on screen readers. [Learn more about input field labels](https://dequeuniversity.com/rules/axe/4.9/aria-input-field-name).", "ARIA_INPUT_FIELD_NAME")
    PSI_ARIA_METER_NAME = ("PSI_ARIA-METER-NAME", "a11y", 0, 1, "audits.aria-meter-name.score", "When a meter element doesn't have an accessible name, screen readers announce it with a generic name, making it unusable for users who rely on screen readers. [Learn how to name `meter` elements](https://dequeuniversity.com/rules/axe/4.9/aria-meter-name).", "ARIA_METER_NAME")
    PSI_ARIA_PROGRESSBAR_NAME = ("PSI_ARIA-PROGRESSBAR-NAME", "a11y", 0, 1, "audits.aria-progressbar-name.score", "When a `progressbar` element doesn't have an accessible name, screen readers announce it with a generic name, making it unusable for users who rely on screen readers. [Learn how to label `progressbar` elements](https://dequeuniversity.com/rules/axe/4.9/aria-progressbar-name).", "ARIA_PROGRESSBAR_NAME")
    PSI_ARIA_PROHIBITED_ATTR = ("PSI_ARIA-PROHIBITED-ATTR", "a11y", 7, 1, "audits.aria-prohibited-attr.score", "Using ARIA attributes in roles where they are prohibited can mean that important information is not communicated to users of assistive technologies. [Learn more about prohibited ARIA roles](https://dequeuniversity.com/rules/axe/4.9/aria-prohibited-attr).", "ARIA_PROHIBITED_ATTR")
    PSI_ARIA_REQUIRED_ATTR = ("PSI_ARIA-REQUIRED-ATTR", "a11y", 10, 1, "audits.aria-required-attr.score", "Some ARIA roles have required attributes that describe the state of the element to screen readers. [Learn more about roles and required attributes](https://dequeuniversity.com/rules/axe/4.9/aria-required-attr).", "ARIA_REQUIRED_ATTR")
    PSI_ARIA_REQUIRED_CHILDREN = ("PSI_ARIA-REQUIRED-CHILDREN", "a11y", 0, 1, "audits.aria-required-children.score", "Some ARIA parent roles must contain specific child roles to perform their intended accessibility functions. [Learn more about roles and required children elements](https://dequeuniversity.com/rules/axe/4.9/aria-required-children).", "ARIA_REQUIRED_CHILDREN")
    PSI_ARIA_REQUIRED_PARENT = ("PSI_ARIA-REQUIRED-PARENT", "a11y", 0, 1, "audits.aria-required-parent.score", "Some ARIA child roles must be contained by specific parent roles to properly perform their intended accessibility functions. [Learn more about ARIA roles and required parent element](https://dequeuniversity.com/rules/axe/4.9/aria-required-parent).", "ARIA_REQUIRED_PARENT")
    PSI_ARIA_ROLES = ("PSI_ARIA-ROLES", "a11y", 7, 1, "audits.aria-roles.score", "ARIA roles must have valid values in order to perform their intended accessibility functions. [Learn more about valid ARIA roles](https://dequeuniversity.com/rules/axe/4.9/aria-roles).", "ARIA_ROLES")
    PSI_ARIA_TEXT = ("PSI_ARIA-TEXT", "a11y", 0, 1, "audits.aria-text.score", "Adding `role=text` around a text node split by markup enables VoiceOver to treat it as one phrase, but the element's focusable descendents will not be announced. [Learn more about the `role=text` attribute](https://dequeuniversity.com/rules/axe/4.9/aria-text).", "ARIA_TEXT")
    PSI_ARIA_TOGGLE_FIELD_NAME = ("PSI_ARIA-TOGGLE-FIELD-NAME", "a11y", 0, 1, "audits.aria-toggle-field-name.score", "When a toggle field doesn't have an accessible name, screen readers announce it with a generic name, making it unusable for users who rely on screen readers. [Learn more about toggle fields](https://dequeuniversity.com/rules/axe/4.9/aria-toggle-field-name).", "ARIA_TOGGLE_FIELD_NAME")
    PSI_ARIA_TOOLTIP_NAME = ("PSI_ARIA-TOOLTIP-NAME", "a11y", 0, 1, "audits.aria-tooltip-name.score", "When a tooltip element doesn't have an accessible name, screen readers announce it with a generic name, making it unusable for users who rely on screen readers. [Learn how to name `tooltip` elements](https://dequeuniversity.com/rules/axe/4.9/aria-tooltip-name).", "ARIA_TOOLTIP_NAME")
    PSI_ARIA_TREEITEM_NAME = ("PSI_ARIA-TREEITEM-NAME", "a11y", 0, 1, "audits.aria-treeitem-name.score", "When a `treeitem` element doesn't have an accessible name, screen readers announce it with a generic name, making it unusable for users who rely on screen readers. [Learn more about labeling `treeitem` elements](https://dequeuniversity.com/rules/axe/4.9/aria-treeitem-name).", "ARIA_TREEITEM_NAME")
    PSI_ARIA_VALID_ATTR_VALUE = ("PSI_ARIA-VALID-ATTR-VALUE", "a11y", 10, 1, "audits.aria-valid-attr-value.score", "Assistive technologies, like screen readers, can't interpret ARIA attributes with invalid values. [Learn more about valid values for ARIA attributes](https://dequeuniversity.com/rules/axe/4.9/aria-valid-attr-value).", "ARIA_VALID_ATTR_VALUE")
    PSI_ARIA_VALID_ATTR = ("PSI_ARIA-VALID-ATTR", "a11y", 10, 1, "audits.aria-valid-attr.score", "Assistive technologies, like screen readers, can't interpret ARIA attributes with invalid names. [Learn more about valid ARIA attributes](https://dequeuniversity.com/rules/axe/4.9/aria-valid-attr).", "ARIA_VALID_ATTR")
    PSI_BUTTON_NAME = ("PSI_BUTTON-NAME", "a11y", 10, 1, "audits.button-name.score", "When a button doesn't have an accessible name, screen readers announce it as 'button', making it unusable for users who rely on screen readers. [Learn how to make buttons more accessible](https://dequeuniversity.com/rules/axe/4.9/button-name).", "BUTTON_NAME")
    PSI_BYPASS = ("PSI_BYPASS", "a11y", 0, 1, "audits.bypass.score", "Adding ways to bypass repetitive content lets keyboard users navigate the page more efficiently. [Learn more about bypass blocks](https://dequeuniversity.com/rules/axe/4.9/bypass).", "BYPASS")
    PSI_COLOR_CONTRAST = ("PSI_COLOR-CONTRAST", "a11y", 7, 1, "audits.color-contrast.score", "Low-contrast text is difficult or impossible for many users to read. [Learn how to provide sufficient color contrast](https://dequeuniversity.com/rules/axe/4.9/color-contrast).", "COLOR_CONTRAST")
    PSI_DEFINITION_LIST = ("PSI_DEFINITION-LIST", "a11y", 0, 1, "audits.definition-list.score", "When definition lists are not properly marked up, screen readers may produce confusing or inaccurate output. [Learn how to structure definition lists correctly](https://dequeuniversity.com/rules/axe/4.9/definition-list).", "DEFINITION_LIST")
    PSI_DLITEM = ("PSI_DLITEM", "a11y", 0, 1, "audits.dlitem.score", "Definition list items (`<dt>` and `<dd>`) must be wrapped in a parent `<dl>` element to ensure that screen readers can properly announce them. [Learn how to structure definition lists correctly](https://dequeuniversity.com/rules/axe/4.9/dlitem).", "DLITEM")
    PSI_DUPLICATE_ID_ARIA = ("PSI_DUPLICATE-ID-ARIA", "a11y", 0, 1, "audits.duplicate-id-aria.score", "The value of an ARIA ID must be unique to prevent other instances from being overlooked by assistive technologies. [Learn how to fix duplicate ARIA IDs](https://dequeuniversity.com/rules/axe/4.9/duplicate-id-aria).", "DUPLICATE_ID_ARIA")
    PSI_FORM_FIELD_MULTIPLE_LABELS = ("PSI_FORM-FIELD-MULTIPLE-LABELS", "a11y", 0, 1, "audits.form-field-multiple-labels.score", "Form fields with multiple labels can be confusingly announced by assistive technologies like screen readers which use either the first, the last, or all of the labels. [Learn how to use form labels](https://dequeuniversity.com/rules/axe/4.9/form-field-multiple-labels).", "FORM_FIELD_MULTIPLE_LABELS")
    PSI_FRAME_TITLE = ("PSI_FRAME-TITLE", "a11y", 0, 1, "audits.frame-title.score", "Screen reader users rely on frame titles to describe the contents of frames. [Learn more about frame titles](https://dequeuniversity.com/rules/axe/4.9/frame-title).", "FRAME_TITLE")
    PSI_HEADING_ORDER = ("PSI_HEADING-ORDER", "a11y", 3, 1, "audits.heading-order.score", "Properly ordered headings that do not skip levels convey the semantic structure of the page, making it easier to navigate and understand when using assistive technologies. [Learn more about heading order](https://dequeuniversity.com/rules/axe/4.9/heading-order).", "HEADING_ORDER")
    PSI_HTML_HAS_LANG = ("PSI_HTML-HAS-LANG", "a11y", 7, 1, "audits.html-has-lang.score", "If a page doesn't specify a `lang` attribute, a screen reader assumes that the page is in the default language that the user chose when setting up the screen reader. If the page isn't actually in the default language, then the screen reader might not announce the page's text correctly. [Learn more about the `lang` attribute](https://dequeuniversity.com/rules/axe/4.9/html-has-lang).", "HTML_HAS_LANG")
    PSI_HTML_LANG_VALID = ("PSI_HTML-LANG-VALID", "a11y", 7, 1, "audits.html-lang-valid.score", "Specifying a valid [BCP 47 language](https://www.w3.org/International/questions/qa-choosing-language-tags#question) helps screen readers announce text properly. [Learn how to use the `lang` attribute](https://dequeuniversity.com/rules/axe/4.9/html-lang-valid).", "HTML_LANG_VALID")
    PSI_HTML_XML_LANG_MISMATCH = ("PSI_HTML-XML-LANG-MISMATCH", "a11y", 0, 1, "audits.html-xml-lang-mismatch.score", "If the webpage does not specify a consistent language, then the screen reader might not announce the page's text correctly. [Learn more about the `lang` attribute](https://dequeuniversity.com/rules/axe/4.9/html-xml-lang-mismatch).", "HTML_XML_LANG_MISMATCH")
    PSI_IMAGE_REDUNDANT_ALT = ("PSI_IMAGE-REDUNDANT-ALT", "a11y", 1, 1, "audits.image-redundant-alt.score", "Informative elements should aim for short, descriptive alternative text. Alternative text that is exactly the same as the text adjacent to the link or image is potentially confusing for screen reader users, because the text will be read twice. [Learn more about the `alt` attribute](https://dequeuniversity.com/rules/axe/4.9/image-redundant-alt).", "IMAGE_REDUNDANT_ALT")
    PSI_INPUT_BUTTON_NAME = ("PSI_INPUT-BUTTON-NAME", "a11y", 0, 1, "audits.input-button-name.score", "Adding discernable and accessible text to input buttons may help screen reader users understand the purpose of the input button. [Learn more about input buttons](https://dequeuniversity.com/rules/axe/4.9/input-button-name).", "INPUT_BUTTON_NAME")
    PSI_INPUT_IMAGE_ALT = ("PSI_INPUT-IMAGE-ALT", "a11y", 0, 1, "audits.input-image-alt.score", "When an image is being used as an `<input>` button, providing alternative text can help screen reader users understand the purpose of the button. [Learn about input image alt text](https://dequeuniversity.com/rules/axe/4.9/input-image-alt).", "INPUT_IMAGE_ALT")
    PSI_LABEL = ("PSI_LABEL", "a11y", 0, 1, "audits.label.score", "Labels ensure that form controls are announced properly by assistive technologies, like screen readers. [Learn more about form element labels](https://dequeuniversity.com/rules/axe/4.9/label).", "LABEL")
    PSI_LINK_IN_TEXT_BLOCK = ("PSI_LINK-IN-TEXT-BLOCK", "a11y", 7, 1, "audits.link-in-text-block.score", "Low-contrast text is difficult or impossible for many users to read. Link text that is discernible improves the experience for users with low vision. [Learn how to make links distinguishable](https://dequeuniversity.com/rules/axe/4.9/link-in-text-block).", "LINK_IN_TEXT_BLOCK")
    PSI_LINK_NAME = ("PSI_LINK-NAME", "a11y", 7, 1, "audits.link-name.score", "Link text (and alternate text for images, when used as links) that is discernible, unique, and focusable improves the navigation experience for screen reader users. [Learn how to make links accessible](https://dequeuniversity.com/rules/axe/4.9/link-name).", "LINK_NAME")
    PSI_LIST = ("PSI_LIST", "a11y", 0, 1, "audits.list.score", "Screen readers have a specific way of announcing lists. Ensuring proper list structure aids screen reader output. [Learn more about proper list structure](https://dequeuniversity.com/rules/axe/4.9/list).", "LIST")
    PSI_LISTITEM = ("PSI_LISTITEM", "a11y", 0, 1, "audits.listitem.score", "Screen readers require list items (`<li>`) to be contained within a parent `<ul>`, `<ol>` or `<menu>` to be announced properly. [Learn more about proper list structure](https://dequeuniversity.com/rules/axe/4.9/listitem).", "LISTITEM")
    PSI_META_REFRESH = ("PSI_META-REFRESH", "a11y", 0, 1, "audits.meta-refresh.score", "Users do not expect a page to refresh automatically, and doing so will move focus back to the top of the page. This may create a frustrating or confusing experience. [Learn more about the refresh meta tag](https://dequeuniversity.com/rules/axe/4.9/meta-refresh).", "META_REFRESH")
    PSI_META_VIEWPORT = ("PSI_META-VIEWPORT", "a11y", 10, 1, "audits.meta-viewport.score", "Disabling zooming is problematic for users with low vision who rely on screen magnification to properly see the contents of a web page. [Learn more about the viewport meta tag](https://dequeuniversity.com/rules/axe/4.9/meta-viewport).", "META_VIEWPORT")
    PSI_OBJECT_ALT = ("PSI_OBJECT-ALT", "a11y", 0, 1, "audits.object-alt.score", "Screen readers cannot translate non-text content. Adding alternate text to `<object>` elements helps screen readers convey meaning to users. [Learn more about alt text for `object` elements](https://dequeuniversity.com/rules/axe/4.9/object-alt).", "OBJECT_ALT")
    PSI_SELECT_NAME = ("PSI_SELECT-NAME", "a11y", 0, 1, "audits.select-name.score", "Form elements without effective labels can create frustrating experiences for screen reader users. [Learn more about the `select` element](https://dequeuniversity.com/rules/axe/4.9/select-name).", "SELECT_NAME")
    PSI_SKIP_LINK = ("PSI_SKIP-LINK", "a11y", 0, 1, "audits.skip-link.score", "Including a skip link can help users skip to the main content to save time. [Learn more about skip links](https://dequeuniversity.com/rules/axe/4.9/skip-link).", "SKIP_LINK")
    PSI_TABINDEX = ("PSI_TABINDEX", "a11y", 0, 1, "audits.tabindex.score", "A value greater than 0 implies an explicit navigation ordering. Although technically valid, this often creates frustrating experiences for users who rely on assistive technologies. [Learn more about the `tabindex` attribute](https://dequeuniversity.com/rules/axe/4.9/tabindex).", "TABINDEX")
    PSI_TABLE_DUPLICATE_NAME = ("PSI_TABLE-DUPLICATE-NAME", "a11y", 0, 1, "audits.table-duplicate-name.score", "The summary attribute should describe the table structure, while `<caption>` should have the onscreen title. Accurate table mark-up helps users of screen readers. [Learn more about summary and caption](https://dequeuniversity.com/rules/axe/4.9/table-duplicate-name).", "TABLE_DUPLICATE_NAME")
    PSI_TARGET_SIZE = ("PSI_TARGET-SIZE", "a11y", 7, 1, "audits.target-size.score", "Touch targets with sufficient size and spacing help users who may have difficulty targeting small controls to activate the targets. [Learn more about touch targets](https://dequeuniversity.com/rules/axe/4.9/target-size).", "TARGET_SIZE")
    PSI_TD_HEADERS_ATTR = ("PSI_TD-HEADERS-ATTR", "a11y", 0, 1, "audits.td-headers-attr.score", "Screen readers have features to make navigating tables easier. Ensuring `<td>` cells using the `[headers]` attribute only refer to other cells in the same table may improve the experience for screen reader users. [Learn more about the `headers` attribute](https://dequeuniversity.com/rules/axe/4.9/td-headers-attr).", "TD_HEADERS_ATTR")
    PSI_TH_HAS_DATA_CELLS = ("PSI_TH-HAS-DATA-CELLS", "a11y", 0, 1, "audits.th-has-data-cells.score", "Screen readers have features to make navigating tables easier. Ensuring table headers always refer to some set of cells may improve the experience for screen reader users. [Learn more about table headers](https://dequeuniversity.com/rules/axe/4.9/th-has-data-cells).", "TH_HAS_DATA_CELLS")
    PSI_VALID_LANG = ("PSI_VALID-LANG", "a11y", 0, 1, "audits.valid-lang.score", "Specifying a valid [BCP 47 language](https://www.w3.org/International/questions/qa-choosing-language-tags#question) on elements helps ensure that text is pronounced correctly by a screen reader. [Learn how to use the `lang` attribute](https://dequeuniversity.com/rules/axe/4.9/valid-lang).", "VALID_LANG")
    PSI_VIDEO_CAPTION = ("PSI_VIDEO-CAPTION", "a11y", 0, 1, "audits.video-caption.score", "When a video provides a caption it is easier for deaf and hearing impaired users to access its information. [Learn more about video captions](https://dequeuniversity.com/rules/axe/4.9/video-caption).", "VIDEO_CAPTION")
    PSI_FOCUSABLE_CONTROLS = ("PSI_FOCUSABLE-CONTROLS", "a11y", 0, 1, "audits.focusable-controls.score", "Custom interactive controls are keyboard focusable and display a focus indicator. [Learn how to make custom controls focusable](https://developer.chrome.com/docs/lighthouse/accessibility/focusable-controls/).", "FOCUSABLE_CONTROLS")
    PSI_INTERACTIVE_ELEMENT_AFFORDANCE = ("PSI_INTERACTIVE-ELEMENT-AFFORDANCE", "a11y", 0, 1, "audits.interactive-element-affordance.score", "Interactive elements, such as links and buttons, should indicate their state and be distinguishable from non-interactive elements. [Learn how to decorate interactive elements with affordance hints](https://developer.chrome.com/docs/lighthouse/accessibility/interactive-element-affordance/).", "INTERACTIVE_ELEMENT_AFFORDANCE")
    PSI_LOGICAL_TAB_ORDER = ("PSI_LOGICAL-TAB-ORDER", "a11y", 0, 1, "audits.logical-tab-order.score", "Tabbing through the page follows the visual layout. Users cannot focus elements that are offscreen. [Learn more about logical tab ordering](https://developer.chrome.com/docs/lighthouse/accessibility/logical-tab-order/).", "LOGICAL_TAB_ORDER")
    PSI_VISUAL_ORDER_FOLLOWS_DOM = ("PSI_VISUAL-ORDER-FOLLOWS-DOM", "a11y", 0, 1, "audits.visual-order-follows-dom.score", "DOM order matches the visual order, improving navigation for assistive technology. [Learn more about DOM and visual ordering](https://developer.chrome.com/docs/lighthouse/accessibility/visual-order-follows-dom/).", "VISUAL_ORDER_FOLLOWS_DOM")
    PSI_FOCUS_TRAPS = ("PSI_FOCUS-TRAPS", "a11y", 0, 1, "audits.focus-traps.score", "A user can tab into and out of any control or region without accidentally trapping their focus. [Learn how to avoid focus traps](https://developer.chrome.com/docs/lighthouse/accessibility/focus-traps/).", "FOCUS_TRAPS")
    PSI_MANAGED_FOCUS = ("PSI_MANAGED-FOCUS", "a11y", 0, 1, "audits.managed-focus.score", "If new content, such as a dialog, is added to the page, the user's focus is directed to it. [Learn how to direct focus to new content](https://developer.chrome.com/docs/lighthouse/accessibility/managed-focus/).", "MANAGED_FOCUS")
    PSI_USE_LANDMARKS = ("PSI_USE-LANDMARKS", "a11y", 0, 1, "audits.use-landmarks.score", "Landmark elements (`<main>`, `<nav>`, etc.) are used to improve the keyboard navigation of the page for assistive technology. [Learn more about landmark elements](https://developer.chrome.com/docs/lighthouse/accessibility/use-landmarks/).", "USE_LANDMARKS")
    PSI_OFFSCREEN_CONTENT_HIDDEN = ("PSI_OFFSCREEN-CONTENT-HIDDEN", "a11y", 0, 1, "audits.offscreen-content-hidden.score", "Offscreen content is hidden with display: none or aria-hidden=true. [Learn how to properly hide offscreen content](https://developer.chrome.com/docs/lighthouse/accessibility/offscreen-content-hidden/).", "OFFSCREEN_CONTENT_HIDDEN")
    PSI_CUSTOM_CONTROLS_LABELS = ("PSI_CUSTOM-CONTROLS-LABELS", "a11y", 0, 1, "audits.custom-controls-labels.score", "Custom interactive controls have associated labels, provided by aria-label or aria-labelledby. [Learn more about custom controls and labels](https://developer.chrome.com/docs/lighthouse/accessibility/custom-controls-labels/).", "CUSTOM_CONTROLS_LABELS")
    PSI_CUSTOM_CONTROLS_ROLES = ("PSI_CUSTOM-CONTROLS-ROLES", "a11y", 0, 1, "audits.custom-controls-roles.score", "Custom interactive controls have appropriate ARIA roles. [Learn how to add roles to custom controls](https://developer.chrome.com/docs/lighthouse/accessibility/custom-control-roles/).", "CUSTOM_CONTROLS_ROLES")
    PSI_EMPTY_HEADING = ("PSI_EMPTY-HEADING", "a11y", 0, 1, "audits.empty-heading.score", "A heading with no content or inaccessible text prevent screen reader users from accessing information on the page's structure. [Learn more about headings](https://dequeuniversity.com/rules/axe/4.9/empty-heading).", "EMPTY_HEADING")
    PSI_IDENTICAL_LINKS_SAME_PURPOSE = ("PSI_IDENTICAL-LINKS-SAME-PURPOSE", "a11y", 0, 1, "audits.identical-links-same-purpose.score", "Links with the same destination should have the same description, to help users understand the link's purpose and decide whether to follow it. [Learn more about identical links](https://dequeuniversity.com/rules/axe/4.9/identical-links-same-purpose).", "IDENTICAL_LINKS_SAME_PURPOSE")
    PSI_LANDMARK_ONE_MAIN = ("PSI_LANDMARK-ONE-MAIN", "a11y", 0, 1, "audits.landmark-one-main.score", "One main landmark helps screen reader users navigate a web page. [Learn more about landmarks](https://dequeuniversity.com/rules/axe/4.9/landmark-one-main).", "LANDMARK_ONE_MAIN")
    PSI_LABEL_CONTENT_NAME_MISMATCH = ("PSI_LABEL-CONTENT-NAME-MISMATCH", "a11y", 0, 1, "audits.label-content-name-mismatch.score", "Visible text labels that do not match the accessible name can result in a confusing experience for screen reader users. [Learn more about accessible names](https://dequeuniversity.com/rules/axe/4.9/label-content-name-mismatch).", "LABEL_CONTENT_NAME_MISMATCH")
    PSI_TABLE_FAKE_CAPTION = ("PSI_TABLE-FAKE-CAPTION", "a11y", 0, 1, "audits.table-fake-caption.score", "Screen readers have features to make navigating tables easier. Ensuring that tables use the actual caption element instead of cells with the `[colspan]` attribute may improve the experience for screen reader users. [Learn more about captions](https://dequeuniversity.com/rules/axe/4.9/table-fake-caption).", "TABLE_FAKE_CAPTION")
    PSI_TD_HAS_HEADER = ("PSI_TD-HAS-HEADER", "a11y", 0, 1, "audits.td-has-header.score", "Screen readers have features to make navigating tables easier. Ensuring that `<td>` elements in a large table (3 or more cells in width and height) have an associated table header may improve the experience for screen reader users. [Learn more about table headers](https://dequeuniversity.com/rules/axe/4.9/td-has-header).", "TD_HAS_HEADER")
    # Google Page Speed insights Technical SEO audits
    PSI_IS_CRAWLABLE = ("PSI_IS-CRAWLABLE", "seo", 4, 1, "audits.is-crawlable.score", "Search engines are unable to include your pages in search results if they don't have permission to crawl them. [Learn more about crawler directives](https://developer.chrome.com/docs/lighthouse/seo/is-crawlable/).", "IS_CRAWLABLE")
    PSI_DOCUMENT_TITLE = ("PSI_DOCUMENT-TITLE", "seo", 1, 1, "audits.document-title.score", "The title gives screen reader users an overview of the page, and search engine users rely on it heavily to determine if a page is relevant to their search. [Learn more about document titles](https://dequeuniversity.com/rules/axe/4.9/document-title).", "DOCUMENT_TITLE")
    PSI_META_DESCRIPTION = ("PSI_META-DESCRIPTION", "seo", 1, 1, "audits.meta-description.score", "Meta descriptions may be included in search results to concisely summarize page content. [Learn more about the meta description](https://developer.chrome.com/docs/lighthouse/seo/meta-description/).", "META_DESCRIPTION")
    PSI_HTTP_STATUS_CODE = ("PSI_HTTP-STATUS-CODE", "seo", 2, 1, "audits.http-status-code.score", "Pages with unsuccessful HTTP status codes may not be indexed properly. [Learn more about HTTP status codes](https://developer.chrome.com/docs/lighthouse/seo/http-status-code/).", "HTTP_STATUS_CODE")
    PSI_LINK_TEXT = ("PSI_LINK-TEXT", "seo", 1, 1, "audits.link-text.score", "Descriptive link text helps search engines understand your content. [Learn how to make links more accessible](https://developer.chrome.com/docs/lighthouse/seo/link-text/).", "LINK_TEXT")
    PSI_CRAWLABLE_ANCHORS = ("PSI_CRAWLABLE-ANCHORS", "seo", 1, 1, "audits.crawlable-anchors.score", "Search engines may use `href` attributes on links to crawl websites. Ensure that the `href` attribute of anchor elements links to an appropriate destination, so more pages of the site can be discovered. [Learn how to make links crawlable](https://support.google.com/webmasters/answer/9112205)", "CRAWLABLE_ANCHORS")
    PSI_ROBOTS_TXT = ("PSI_ROBOTS-TXT", "seo", 1, 1, "audits.robots-txt.score", "If your robots.txt file is malformed, crawlers may not be able to understand how you want your website to be crawled or indexed. [Learn more about robots.txt](https://developer.chrome.com/docs/lighthouse/seo/invalid-robots-txt/).", "ROBOTS_TXT")
    PSI_IMAGE_ALT = ("PSI_IMAGE-ALT", "seo", 1, 1, "audits.image-alt.score", "Informative elements should aim for short, descriptive alternate text. Decorative elements can be ignored with an empty alt attribute. [Learn more about the `alt` attribute](https://dequeuniversity.com/rules/axe/4.9/image-alt).", "IMAGE_ALT")
    PSI_HREFLANG = ("PSI_HREFLANG", "seo", 1, 1, "audits.hreflang.score", "hreflang links tell search engines what version of a page they should list in search results for a given language or region. [Learn more about `hreflang`](https://developer.chrome.com/docs/lighthouse/seo/hreflang/).", "HREFLANG")
    PSI_CANONICAL = ("PSI_CANONICAL", "seo", 1, 1, "audits.canonical.score", "Canonical links suggest which URL to show in search results. [Learn more about canonical links](https://developer.chrome.com/docs/lighthouse/seo/canonical/).", "CANONICAL")
    PSI_STRUCTURED_DATA = ("PSI_STRUCTURED-DATA", "seo", 0, 1, "audits.structured-data.score", "Run the [Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool/) and the [Structured Data Linter](http://linter.structured-data.org/) to validate structured data. [Learn more about Structured Data](https://developer.chrome.com/docs/lighthouse/seo/structured-data/).", "STRUCTURED_DATA")
    PSI_IS_ON_HTTPS = ("PSI_IS-ON-HTTPS", "seo", 3, 1, "audits.is-on-https.score", "All sites should be protected with HTTPS, even ones that don't handle sensitive data. This includes avoiding [mixed content](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content), where some resources are loaded over HTTP despite the initial request being served over HTTPS. HTTPS prevents intruders from tampering with or passively listening in on the communications between your app and your users, and is a prerequisite for HTTP/2 and many new web platform APIs. [Learn more about HTTPS](https://developer.chrome.com/docs/lighthouse/pwa/is-on-https/).", "IS_ON_HTTPS")
    PSI_REDIRECTS_HTTP = ("PSI_REDIRECTS-HTTP", "seo", 0, 1, "audits.redirects-http.score", "Make sure that you redirect all HTTP traffic to HTTPS in order to enable secure web features for all your users. [Learn more](https://developer.chrome.com/docs/lighthouse/pwa/redirects-http/).", "REDIRECTS_HTTP")
    PSI_GEOLOCATION_ON_START = ("PSI_GEOLOCATION-ON-START", "seo", 1, 1, "audits.geolocation-on-start.score", "Users are mistrustful of or confused by sites that request their location without context. Consider tying the request to a user action instead. [Learn more about the geolocation permission](https://developer.chrome.com/docs/lighthouse/best-practices/geolocation-on-start/).", "GEOLOCATION_ON_START")
    PSI_NOTIFICATION_ON_START = ("PSI_NOTIFICATION-ON-START", "seo", 3, 1, "audits.notification-on-start.score", "Users are mistrustful of or confused by sites that request to send notifications without context. Consider tying the request to user gestures instead. [Learn more about responsibly getting permission for notifications](https://developer.chrome.com/docs/lighthouse/best-practices/notification-on-start/).", "NOTIFICATION_ON_START")
    PSI_CSP_XSS = ("PSI_CSP-XSS", "seo", 0, 1, "audits.csp-xss.score", "A strong Content Security Policy (CSP) significantly reduces the risk of cross-site scripting (XSS) attacks. [Learn how to use a CSP to prevent XSS](https://developer.chrome.com/docs/lighthouse/best-practices/csp-xss/)", "CSP_XSS")
    PSI_PASTE_PREVENTING_INPUTS = ("PSI_PASTE-PREVENTING-INPUTS", "seo", 1, 1, "audits.paste-preventing-inputs.score", "Preventing input pasting is a bad practice for the UX, and weakens security by blocking password managers.[Learn more about user-friendly input fields](https://developer.chrome.com/docs/lighthouse/best-practices/paste-preventing-inputs/).", "PASTE_PREVENTING_INPUTS")
    PSI_IMAGE_ASPECT_RATIO = ("PSI_IMAGE-ASPECT-RATIO", "seo", 1, 1, "audits.image-aspect-ratio.score", "Image display dimensions should match natural aspect ratio. [Learn more about image aspect ratio](https://developer.chrome.com/docs/lighthouse/best-practices/image-aspect-ratio/).", "IMAGE_ASPECT_RATIO")
    PSI_IMAGE_SIZE_RESPONSIVE = ("PSI_IMAGE-SIZE-RESPONSIVE", "seo", 1, 1, "audits.image-size-responsive.score", "Image natural dimensions should be proportional to the display size and the pixel ratio to maximize image clarity. [Learn how to provide responsive images](https://web.dev/articles/serve-responsive-images).", "IMAGE_SIZE_RESPONSIVE")
    PSI_VIEWPORT = ("PSI_VIEWPORT", "seo", 1, 1, "audits.viewport.score", "A `<meta name='viewport'>` not only optimizes your app for mobile screen sizes, but also prevents [a 300 millisecond delay to user input](https://developer.chrome.com/blog/300ms-tap-delay-gone-away/). [Learn more about using the viewport meta tag](https://developer.chrome.com/docs/lighthouse/pwa/viewport/).", "VIEWPORT")
    PSI_FONT_SIZE = ("PSI_FONT-SIZE", "seo", 1, 1, "audits.font-size.score", "Font sizes less than 12px are too small to be legible and require mobile visitors to “pinch to zoom” in order to read. Strive to have >60% of page text ≥12px. [Learn more about legible font sizes](https://developer.chrome.com/docs/lighthouse/seo/font-size/).", "FONT_SIZE")
    PSI_DOCTYPE = ("PSI_DOCTYPE", "seo", 1, 1, "audits.doctype.score", "Specifying a doctype prevents the browser from switching to quirks-mode. [Learn more about the doctype declaration](https://developer.chrome.com/docs/lighthouse/best-practices/doctype/).", "DOCTYPE")
    PSI_CHARSET = ("PSI_CHARSET", "seo", 1, 1, "audits.charset.score", "A character encoding declaration is required. It can be done with a `<meta>` tag in the first 1024 bytes of the HTML or in the Content-Type HTTP response header. [Learn more about declaring the character encoding](https://developer.chrome.com/docs/lighthouse/best-practices/charset/).", "CHARSET")
    PSI_DEPRECATIONS = ("PSI_DEPRECATIONS", "seo", 5, 1, "audits.deprecations.score", "Deprecated APIs will eventually be removed from the browser. [Learn more about deprecated APIs](https://developer.chrome.com/docs/lighthouse/best-practices/deprecations/).", "DEPRECATIONS")
    PSI_THIRD_PARTY_COOKIES = ("PSI_THIRD-PARTY-COOKIES", "seo", 1, 1, "audits.third-party-cookies.score", "Support for third-party cookies will be removed in a future version of Chrome. [Learn more about phasing out third-party cookies](https://developer.chrome.com/en/docs/privacy-sandbox/third-party-cookie-phase-out/).", "THIRD_PARTY_COOKIES")
    PSI_ERRORS_IN_CONSOLE = ("PSI_ERRORS-IN-CONSOLE", "seo", 1, 1, "audits.errors-in-console.score", "Errors logged to the console indicate unresolved problems. They can come from network request failures and other browser concerns. [Learn more about this errors in console diagnostic audit](https://developer.chrome.com/docs/lighthouse/best-practices/errors-in-console/)", "ERRORS_IN_CONSOLE")
    PSI_VALID_SOURCE_MAPS = ("PSI_VALID-SOURCE-MAPS", "seo", 0, 1, "audits.valid-source-maps.score", "Source maps translate minified code to the original source code. This helps developers debug in production. In addition, Lighthouse is able to provide further insights. Consider deploying source maps to take advantage of these benefits. [Learn more about source maps](https://developer.chrome.com/docs/devtools/javascript/source-maps/).", "VALID_SOURCE_MAPS")
    PSI_INSPECTOR_ISSUES = ("PSI_INSPECTOR-ISSUES", "seo", 1, 1, "audits.inspector-issues.score", "Issues logged to the `Issues` panel in Chrome Devtools indicate unresolved problems. They can come from network request failures, insufficient security controls, and other browser concerns. Open up the Issues panel in Chrome DevTools for more details on each issue.", "INSPECTOR_ISSUES")

    def __new__(cls, value, category, category_weight, global_weight, psi_path, description):
        """Add the path in dict to get the value (from psi insights audit)."""
        obj = str.__new__(cls, value)
        obj._value_ = value
        obj.category = category
        obj.category_weight = category_weight
        obj.global_weight = global_weight
        obj.psi_path = psi_path
        obj.description = description
        return obj

    @classmethod
    def get_psi_audits(cls) -> list:
        """Return the list of PSI audits."""
        return [cls(audit) for audit in cls.values if audit.startswith("PSI_")]


